SELECT PROJECT_NAME AS NAME, TIMESTAMPDIFF(MONTH, START_DATE, FINISH_DATE) AS MONTH_COUNT
FROM project
WHERE TIMESTAMPDIFF(MONTH, START_DATE, FINISH_DATE) = (
    SELECT MAX(project_duration)
    FROM (
        SELECT TIMESTAMPDIFF(MONTH, START_DATE, FINISH_DATE) AS project_duration
        FROM project
    ) AS project_durations
);