SELECT 'YOUNGEST' AS TYPE, NAME, BIRTHDAY
FROM (
    SELECT NAME, BIRTHDAY, FIRST_VALUE(BIRTHDAY) OVER (ORDER BY BIRTHDAY ASC) AS min_birthday
    FROM worker
) youngest
WHERE BIRTHDAY = min_birthday
UNION
SELECT 'OLDEST' AS TYPE, NAME, BIRTHDAY
FROM (
    SELECT NAME, BIRTHDAY, FIRST_VALUE(BIRTHDAY) OVER (ORDER BY BIRTHDAY DESC) AS max_birthday
    FROM worker
) oldest
WHERE BIRTHDAY = max_birthday;